# Generated by Django 3.2.12 on 2023-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_all_users', 'Can view all users'), ('edit_settings', 'Can edit application settings')],
            },
        ),
    ]
