# Generated by Django 3.2.12 on 2023-08-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModel',
        ),
    ]
