# Generated by Django 3.2.12 on 2023-08-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0006_category_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='category',
            new_name='parent_category',
        ),
    ]
