# Generated by Django 3.2.12 on 2023-08-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0010_alter_blog_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='name',
        ),
    ]
