# Generated by Django 3.2.12 on 2023-08-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0011_remove_sub_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customAdmin.category'),
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
