# Generated by Django 3.2.12 on 2023-08-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0012_auto_20230817_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='category_name',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customAdmin.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
