# Generated by Django 3.2.12 on 2023-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0015_auto_20230818_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='uncategorized', max_length=300),
        ),
    ]
