# Generated by Django 3.2.12 on 2023-08-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0019_auto_20230818_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
