# Generated by Django 3.2.12 on 2023-08-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0021_blog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tags',
            new_name='tag',
        ),
    ]
