# Generated by Django 3.2.12 on 2023-08-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0022_rename_tags_blog_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='customAdmin.tag'),
        ),
    ]
