# Generated by Django 3.2.12 on 2023-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0023_auto_20230821_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
